apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp-nginx
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx:latest
    - ports:
        port: 80
        targetport: 30004
This is k8s practice file in branch1
05Nov2021--Added new practice line in branch1.
